# fork = false
# frame = "full"
frame = "transparent"
# idle = true
maximized = false
# mouse-cursor-icon = "arrow"
# neovim-bin = "/Users/jlima/.local/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = true
tabs = true
theme = "dark"
title-hidden = true
vsync = true
wsl = false

[font]
# Will use the bundled Fira Code Nerd Font by default
# normal = { family = "SF Mono Terminal", style = "Medium" }
# normal = { family = "IosevkaTerm Nerd Font Mono", style = "Medium" }
# normal = { family = "Iosevka Mayukai Original", style = "Medium" }

normal = { family = "Iosevka Custom", style = "Medium" }

# features = { "IosevkaTerm Nerd Font Mono" = ["-calt", "-liga", "-dlig"] }
size = 24
width = 1.5

# best for macos...
hinting = "none"
